version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:16
    hostname: postgres
    container_name: memora
    restart: unless-stopped

    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
